[build]
  publish = "."                # Publica desde el directorio raíz
  functions = "netlify/functions"
  command = "npm install"      # Instala dependencias sin build adicional

[[headers]]
  for = "/audio/fondo.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
