[build]
  publish = "."               # Esto le dice a Netlify: "publicá el directorio raíz"
  functions = "netlify/functions"
  command = "npm install"     # O podés dejarlo vacío si no hay build como tal

[[headers]]
  for = "/audio/fondo.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
