[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/audio/fondo.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
