[build]
  publish = "."                 # Publica desde el directorio raíz
  functions = "netlify/functions"
  command = "npm run build"     # Ejecuta el script de build en package.json

[[headers]]
  for = "/audio/fondo.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"

